from pathlib import Path
import runpy
runpy.run_path(str(Path(__file__).with_name('build_demo.py')))
from html import escape
import re
p=Path(__file__).parent / 'docs'
def code(s): return '<div class="code"><button class="copy" type="button">Copiar código</button><pre><code>'+escape(s.strip())+'</code></pre><span class="copy-status" role="status"></span></div>'
def note(title,s): return f'<aside class="note"><strong>{title}</strong><p>{s}</p></aside>'
def cards(items): return '<div class="cards">'+''.join(f'<a class="card" href="#{i}"><span class="kicker">{k}</span><h3>{t}</h3><p>{d}</p><span class="card-link">{l}</span></a>' for i,k,t,d,l in items)+'</div>'
def steps(items): return '<ol class="steps">'+''.join(f'<li><div><h3>{a}</h3><p>{b}</p></div></li>' for a,b in items)+'</ol>'
def table(head,rows): return '<div class="table-wrap"><table><thead><tr>'+''.join('<th scope="col">'+x+'</th>' for x in head)+'</tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+x+'</td>' for x in row)+'</tr>' for row in rows)+'</tbody></table></div>'
sections=[]
def section(id,kicker,title,lead,body): sections.append((id,title,f'<section id="{id}" class="page" aria-labelledby="title-{id}"><div class="eyebrow">{kicker}</div><h1 id="title-{id}" tabindex="-1">{title}</h1><p class="lead">{lead}</p>{body}</section>'))
section('inicio','Manual de trabajo / Brandslab','Contenidos HTML, de principio a fin','Una guía común para coordinar, entregar y publicar contenidos de Branded Content en los medios del grupo.',
cards([('pms','01 / Coordinación','Soy PM','Qué pedir, qué revisar y cuándo está listo un contenido. Sin necesidad de leer código.','Ver el recorrido PM'),('entregas','02 / Producción','Soy proveedor','Qué entregar y cómo asegurar que la maqueta convive con la web del medio.','Ver entregas y requisitos')])+'''
<div class="section-heading"><h2>Un proceso, dos formas de entregar</h2><a href="#entregas">Comparar responsabilidades</a></div>
<div class="flow"><div><span>01</span><strong>Preparar</strong><p>Brief y materiales</p></div><div><span>02</span><strong>Diseñar</strong><p>Mockup y OK del cliente</p></div><div><span>03</span><strong>Maquetar</strong><p>URL externa y revisión</p></div><div><span>04</span><strong>Publicar</strong><p>Xalok y comprobación final</p></div></div>
<div class="split"><div><h2>La Vanguardia</h2><p>Proceso de integración con capturas y criterios técnicos comprobados en contenidos del medio.</p><a class="text-link" href="#xalok">Consultar integración en LV</a></div><div><span class="badge pending">Por validar</span><h2>Mundo Deportivo</h2><p>Comparte los criterios de entrega y revisión. Los pasos de su CMS y los ajustes de plantilla se documentarán por separado.</p><span class="unavailable-label">Próximamente</span></div></div>
'''+note('Guía de trabajo','Una referencia compartida para coordinar el diseño, la aprobación, la entrega y la publicación de contenidos HTML de Branded Content.'))
section('pms','Recorrido PM / Coordinación','Qué pedir y cómo llevar el proyecto','El PM prepara los materiales, canaliza el feedback del cliente y confirma las aprobaciones. El proveedor desarrolla la pieza y comprueba su funcionamiento.',
steps([('Preparar un brief completo','Indica al proveedor en qué medio se publicará el contenido: La Vanguardia (LV), Mundo Deportivo (MD) o ambos. Entrega el objetivo, el formato, el público, los mensajes principales y las indicaciones del cliente. Añade los textos, imágenes, vídeos, logotipos, identidad de marca, créditos y enlaces necesarios. Identifica cualquier material provisional y acuerda cuándo llegará el definitivo.'),('Acordar alcance, calendario y responsables','Confirma quién diseña, quién maqueta y quién se encarga de integrar y programar en Xalok. La integración y la programación las realiza la misma persona. Acuerda las fechas de diseño, feedback, maqueta funcional y entrega final, el número de rondas incluidas y quién da el OK del cliente. Prevé aproximadamente 1–2 días entre la entrega final y la publicación para integrar, revisar y programar.'),('Validar el diseño antes de maquetar','Pide un diseño de la web, preferiblemente en Figma, con escritorio y móvil. Envía al cliente el enlace de visualización, recoge su feedback e intenta agrupar los cambios cuando el tiempo de ejecución lo permita. Solo se inicia la maquetación tras la aprobación del diseño y los contenidos de esa versión.'),('Revisar la maqueta funcional','El proveedor entrega una URL externa accesible al cliente. El PM compara la web con el diseño aprobado, prueba enlaces y contenidos y canaliza la revisión del cliente. Figma valida el diseño; esta URL permite comprobar la web funcionando.'),('Cerrar correcciones y aprobación','Los cambios pueden llegar en varios envíos. Intenta agruparlos antes de remitirlos al proveedor cuando el tiempo de ejecución lo permita, manteniendo claro qué está solicitado y qué está resuelto. Distingue errores de implementación de peticiones nuevas. Confirma el impacto en plazo y alcance antes de incorporar cambios sobre un diseño ya aprobado. Conserva el OK del cliente y la referencia de la versión final.'),('Preparar la integración y la salida','Indica el medio en el que se publicará el contenido —LV, MD o ambos— y facilita sección, titular y descripción SEO. Las palabras clave deben incluir siempre brl al final. Especifica si lleva streaming: cuando el contenido incluye un vídeo largo, se añade la palabra streaming o se selecciona la opción correspondiente en Xalok para evitar que la página se recargue automáticamente. Confirma la fecha con quien programa: la salida habitual es aproximadamente a las 05:50. El equipo o proveedor con acceso comprueba la integración en Xalok antes de programar.'),('Revisar después de publicar','Abre la URL final en móvil y escritorio, revisa los enlaces y el contenido y confirma la salida al equipo. Si hay incidencias, envía al responsable la URL, una descripción y una captura. La verificación técnica corresponde al proveedor o al responsable de integración.')])+
note('Xalok es una revisión interna','El cliente no tiene acceso a la previsualización de Xalok. Para aprobar el diseño recibe un enlace de Figma; para revisar la maqueta funcional recibe una URL externa. Esto se aplica a las dos modalidades de proveedor.')+
'<h2>Materiales para arrancar</h2>'+table(['El PM entrega','Qué debe quedar claro'],[['Brief y alcance','Objetivo, público, medio de publicación (LV, MD o ambos), formato, secciones de contenido y funcionalidades previstas.'],['Textos y enlaces','Documento con la última versión, jerarquía del contenido y destino de cada botón.'],['Material gráfico y audiovisual','Imágenes con calidad suficiente, vídeos o enlaces de reproducción, logotipos, referencias de marca y créditos.'],['Referencias y condiciones','Qué debe respetarse, qué evitar y qué materiales o funcionalidades son provisionales.'],['Calendario y aprobaciones','Fechas de entrega y feedback, rondas incluidas, interlocutor del cliente y responsables de diseño y desarrollo. Una misma persona integra y programa en Xalok, con aproximadamente 1–2 días de margen antes de publicar.']])+
'<h2>Antes de dar el OK final</h2><ul class="checklist"><li>Diseño y contenidos aprobados antes de maquetar.</li><li>La URL externa abre para el cliente y muestra la última versión.</li><li>Textos, marca, imágenes y créditos coinciden con lo aprobado.</li><li>Botones, enlaces, vídeo y navegación funcionan en móvil y escritorio.</li><li>No hay contenidos provisionales que aparenten estar terminados.</li><li>Se dispone del medio de publicación, los datos SEO, las palabras clave con brl al final y la indicación de si lleva streaming.</li><li>La integración en Xalok tiene responsable y ha sido revisada.</li><li>Fecha de salida y revisión posterior asignadas.</li></ul>'+
'<h2>Las palabras que encontrarás</h2>'+table(['Término','Qué significa para el PM'],[['Diseño / mockup','Propuesta visual de la web antes de programarla, habitualmente compartida desde Figma.'],['Maqueta funcional / preview externa','La web ya desarrollada en un enlace que el cliente puede abrir para revisarla.'],['HTML','El archivo de código que se integra en la noticia; no es el diseño de Figma.'],['CSS / JavaScript','Los estilos visuales y el comportamiento de la web.'],['Recursos o assets','Imágenes, vídeos, fuentes y archivos que necesita la pieza.'],['GitHub / GitHub Pages','El repositorio guarda archivos y versiones; GitHub Pages puede servir esos archivos mediante URLs públicas.'],['Xalok','El CMS desde el que el equipo autorizado integra y programa la noticia.'],['SEO / metas','Información editorial que se configura para identificar y describir la noticia.'],['Streaming','Configuración para contenidos con vídeo largo que evita la recarga automática de la página. Se añade la palabra streaming o se selecciona la opción en Xalok; brl permanece siempre al final de las palabras clave.'],['QA / revisión','Comprobaciones de contenido, diseño y funcionamiento.']]))
section('diseno','Diseño / Aprobación del cliente','Primero el diseño, después la maquetación','El diseño permite acordar estructura, aspecto y experiencia antes de invertir en el desarrollo de la web.',
steps([('Diseñar con el material del proyecto','Partir del brief y de los textos y recursos facilitados por el PM. Resolver la estructura, la jerarquía, las versiones de escritorio y móvil y el comportamiento previsto de elementos como capítulos, vídeos o menús.'),('Compartir un mockup en Figma','Se recomienda Figma para preparar el diseño y compartirlo con el cliente por medio del PM. Entregar un enlace de visualización o prototipo con acceso comprobado. Identificar la versión y explicar las interacciones que una imagen estática no puede mostrar.'),('Recoger feedback por rondas','El PM centraliza los comentarios del cliente y del equipo y resuelve indicaciones contradictorias. Puede haber varios envíos de cambios; se intenta agruparlos cuando el tiempo de ejecución lo permite. Para cada ronda se acuerdan fecha de respuesta y fecha de actualización; el número de rondas depende del alcance pactado.'),('Cerrar el diseño aprobado','El PM obtiene y conserva el OK del cliente sobre la versión concreta. El equipo de desarrollo recibe esa referencia, los recursos exportables y las indicaciones de comportamiento. Señalar de forma explícita cualquier material aún provisional.'),('Maquetar y revisar la web real','El proveedor desarrolla la pieza y publica una URL de prueba externa accesible al cliente. Se compara con el diseño aprobado y se revisan las interacciones reales. Una aprobación de Figma no sustituye la revisión de la web terminada.')])+
'<h2>Qué revisar en el diseño</h2><ul class="checklist"><li>Estructura y orden de lectura claros, en escritorio y móvil.</li><li>Textos reales o provisionales claramente identificados.</li><li>Identidad del cliente, identificación comercial y créditos previstos.</li><li>Destinos y estados de botones y enlaces: activo, seleccionado y próximamente cuando corresponda.</li><li>Comportamiento de vídeo, navegación y animaciones explicado.</li><li>Legibilidad, contraste y tamaños que faciliten la lectura.</li><li>Recursos y tipografías identificados para la entrega a desarrollo.</li></ul>'+
note('Cambios después del OK','Si el cliente pide una nueva sección, otra estructura o una funcionalidad no acordada, el PM debe confirmar con el proveedor el impacto antes de incorporarla. Una corrección para respetar el diseño aprobado no es lo mismo que una ampliación del proyecto.')+
'<p><a class="text-link" href="https://www.figma.com/design/" target="_blank" rel="noopener">Consultar Figma Design</a></p>')
section('entregas','Proveedores / Responsabilidades','Dos circuitos, la misma calidad de entrega','El proveedor utiliza su propio repositorio y proceso de desarrollo. La entrega debe permitir revisar, integrar y mantener la pieza sin reconstruirla.',
'<div class="split"><div><span class="badge">Modalidad A</span><h2>Entrega del HTML</h2><p>El proveedor entrega el <code>index.html</code> preparado para copiar y pegar. El PM o la persona interna designada integra y programa la noticia en Xalok.</p><p>El proveedor facilita una URL de prueba externa para que el PM y el cliente revisen la maqueta.</p></div><div><span class="badge">Modalidad B</span><h2>Entrega en Xalok</h2><p>El proveedor integra el contenido y programa la noticia con su acceso al CMS, una vez recibido el OK y los datos necesarios del PM.</p><p>También entrega una URL externa para la revisión del cliente. La preview de Xalok se utiliza solo dentro del equipo con acceso.</p></div></div>'+
table(['Trabajo','Entrega del HTML','Entrega en Xalok'],[['Brief, textos y materiales','PM','PM'],['Diseño y sus revisiones','Responsable de diseño acordado; PM coordina al cliente','Responsable de diseño acordado; PM coordina al cliente'],['Aprobación del diseño antes de maquetar','Cliente, canalizada por el PM','Cliente, canalizada por el PM'],['Desarrollo y recursos en su repositorio','Proveedor','Proveedor'],['URL externa para revisión','Proveedor','Proveedor'],['OK de la maqueta funcional','Cliente, canalizado por el PM','Cliente, canalizado por el PM'],['Datos editoriales y de programación','PM','PM'],['Inserción en Xalok y programación','PM o persona interna designada','Proveedor con acceso'],['Comprobación técnica en Xalok','Responsable de integración; proveedor corrige su código','Proveedor; equipo valida el resultado'],['Revisión tras publicar','PM revisa contenido; responsable técnico verifica funcionamiento','PM revisa contenido; proveedor verifica funcionamiento']])+
'<p>En ambas modalidades, una misma persona integra y programa en Xalok. La entrega final debe prever aproximadamente 1–2 días para integración y revisión antes de la publicación.</p><h2>Qué debe recibir el proveedor antes de empezar</h2><p>El brief, los textos, los recursos, los enlaces, el alcance y el calendario salen del PM. Si falta material esencial, el proveedor debe señalarlo y acordar cómo afecta a la entrega. Antes de maquetar, debe disponer del diseño aprobado y sus indicaciones de comportamiento.</p>'+
'<p><a class="text-link" href="#descargas">Consultar el ejemplo de HTML preparado para Xalok</a></p><h2>Qué debe entregar el proveedor</h2><ul class="checklist"><li>URL externa accesible con la última maqueta funcional y una referencia clara de versión.</li><li>En la modalidad A, archivo HTML final listo para Xalok, sin que el PM tenga que adaptar rutas o separar etiquetas.</li><li>En la modalidad B, integración revisada, confirmación de programación y URL final.</li><li>Repositorio y carpeta del proyecto identificados, con los recursos definitivos publicados.</li><li>Resumen de comprobaciones y aviso de cualquier incidencia o material sin cerrar.</li><li>Instrucciones necesarias para mantener la pieza, incluidas dependencias si las hay.</li><li>Contacto para las correcciones y la revisión de publicación.</li></ul>'+
note('Distinguir el archivo para Xalok de la página de prueba','Si se entrega una página completa de preview además del fragmento integrable, identifícalos por separado. El index.html destinado al PM debe estar preparado para copiar su código a Xalok. Un HTML con dependencias relativas puede verse bien en el equipo del proveedor y fallar en el medio.')+
'<h2>Ficha de entrega recomendada</h2><p>Es una ayuda, no un documento obligatorio. La información puede quedar en el README, en un correo o en el canal habitual, siempre que el equipo encuentre la versión final y las instrucciones necesarias.</p>'+code("""Proyecto y medio de publicación (LV, MD o ambos):
Modalidad: entrega HTML / entrega en Xalok
Versión de diseño aprobada:
URL externa de la maqueta funcional:
Versión o fecha de entrega:
Repositorio y carpeta:
Archivo listo para Xalok (modalidad A):
Base pública de recursos:
Comprobaciones y notas de mantenimiento:
Incidencias o materiales por cerrar:
Responsable de integración y programación (misma persona):
Entrega final (prever 1–2 días para integrar y revisar):
Fecha de publicación (hora habitual: 05:50 aprox.):
Contacto para incidencias:
URL final y confirmación de programación (cuando estén disponibles):"""))
section('requisitos','Desarrollo / Compatibilidad','Libertad de herramientas. Entrega compatible.','El código entregado debe funcionar en Xalok, ser mantenible y respetar el resto de la página. El equipo elige las herramientas y la estructura interna que mejor encajen con el proyecto.',
'<h2>01. Aislar la pieza</h2><p>Usa un contenedor propio y selectores específicos. Este es un patrón de referencia; un aislamiento equivalente también es válido. No apliques resets globales ni alteres <code>html</code> o <code>body</code> para resolver problemas internos.</p>'+code('''<div class="bc-proyecto" data-bc-project="proyecto">
  <!-- Contenido de la pieza -->
</div>

<style>
.bc-proyecto { --bc-color: #b00000; }
.bc-proyecto *,
.bc-proyecto *::before,
.bc-proyecto *::after { box-sizing: border-box; }
.bc-proyecto img { max-width: 100%; height: auto; }
</style>''')+
'<p>Limita las búsquedas y modificaciones de JavaScript al contenedor. Evita variables globales y listeners innecesarios; no manipules módulos del medio.</p>'+code('''(() => {
  const root = document.querySelector('[data-bc-project="proyecto"]');
  if (!root) return;
  const buttons = root.querySelectorAll('[data-action]');
  // Inicializar únicamente las interacciones de la pieza.
})();''')+
'<h2>02. Entregar recursos que funcionen desde LV</h2><p>Los <code>src</code> y <code>href</code> de recursos pegados en Xalok deben apuntar a su URL pública definitiva por HTTPS. <code>assets/img/foto.webp</code> en el HTML se resolvería desde la URL de la noticia, no desde el repositorio del proveedor.</p><p>Las rutas <code>url(../img/fondo.webp)</code> dentro de un CSS externo se resuelven respecto a ese CSS y pueden ser válidas. En JavaScript hay que comprobar cómo se resuelven las URLs dinámicas. Las anclas como <code>#capitulo-1</code> son navegación interna, no rutas de archivos.</p><p>Cada proveedor utiliza su propio repositorio. No se debe copiar la ruta de otro proyecto como base de una pieza nueva.</p>'+
'<h2>03. Mantener el contenido accesible</h2><ul><li>El contenido esencial permanece visible y usable si falla la animación o su dependencia.</li><li>Respetar la preferencia de movimiento reducido y permitir navegación por teclado con foco visible.</li><li>Utilizar botones para acciones y enlaces para navegación; dar nombres comprensibles a los controles.</li><li>Describir imágenes informativas y marcar las decorativas con alt vacío. Dar título a los iframes.</li><li>Revisar jerarquía de encabezados en el contexto final del medio, IDs únicos y contraste.</li></ul>'+
'<h2>04. Probar scroll y cambios de altura</h2><p>La publicidad, las fuentes, las imágenes y los módulos del medio pueden desplazar la pieza después de cargar. No bases el comportamiento en posiciones calculadas una sola vez. Prueba scroll rápido, anclas y entrada directa a una sección.</p><p><code>sticky</code>, <code>fixed</code> y animaciones ligadas al scroll no están prohibidos: requieren prueba dentro de Xalok. Para reveals sencillos, IntersectionObserver es una opción; otras soluciones son válidas si cumplen las mismas condiciones.</p>'+
'<h2>05. Cuidar carga y mantenimiento</h2><ul><li>Dimensionar y comprimir imágenes según su uso; evitar vídeo pesado con carga inmediata innecesaria.</li><li>Eliminar librerías sin uso y evitar duplicaciones con recursos del medio.</li><li>Si se utiliza un sistema de compilación, entregar los archivos finales que el navegador puede ejecutar y documentar cómo regenerarlos.</li><li>No añadir medición, etiquetas o scripts de terceros sin coordinarlo con el equipo responsable.</li></ul>'+
note('La compatibilidad se comprueba en la entrega','El proveedor debe entregar recursos utilizables por el navegador y un HTML preparado para el CMS. Las pruebas se hacen tanto en la maqueta externa como dentro del medio.'))
fix=Path(__file__).with_name('referencia-lv.css').read_text()
section('xalok','La Vanguardia / Tutorial de integración','Del HTML a la noticia en Xalok','Para el PM o la persona interna que integra una entrega HTML. También sirve como referencia para el proveedor que ya trabaja dentro del CMS.',
note('Antes de abrir Xalok','La maqueta funcional debe estar revisada y aprobada. Prepara el HTML final y los datos de programación: medio de publicación (LV, MD o ambos), sección, titular y descripción SEO, palabras clave terminadas en brl, indicación de si lleva streaming y fecha de salida. Una misma persona integra y programa; reserva aproximadamente 1–2 días antes de publicar para integrar y revisar. La hora habitual es aproximadamente las 05:50.')+
'<h2>1. Comprobar el HTML recibido</h2><p>Descarga el archivo y, si viene en un ZIP, extrae el paquete completo. Haz doble clic en el HTML para abrirlo en el navegador y comprobar que se ve bien. Recorre la página y prueba los enlaces principales.</p><p>Esta comprobación local no sustituye la URL externa ni la prueba en Xalok. Si no carga algún recurso o comportamiento al abrirlo así, pide al proveedor que lo revise y confirme que el archivo entregado está preparado para integrar; algunas funciones necesitan servirse desde una URL web.</p><p>Para copiar el código, abre ese mismo archivo con un editor de texto o código —clic derecho y «Abrir con»—, selecciona todo y copia. No copies el contenido visible de la página desde el navegador.</p>'+
'<h2>2. Crear un contenido de tipo Visual story</h2><p>En la cabecera correspondiente, abre el menú <strong>Contenido</strong> y elige <strong>Visual story</strong> para crear la nueva pieza.</p>'+
'<figure class="tutorial-shot"><a href="images/xalok-01-visual-story.jpeg" target="_blank" rel="noopener" aria-label="Ampliar captura: menú Contenido, Visual story"><img src="images/xalok-01-visual-story.jpeg" width="1600" height="759" alt="Menú Contenido de Xalok desplegado, con Visual story al final de la lista" loading="lazy"></a><figcaption>Menú Contenido · Elegir Visual story <span>Haz clic en la captura para ampliarla</span></figcaption></figure>'+
'<h2>3. Elegir la plantilla Libre</h2><p>En las opciones de plantilla, selecciona <strong>Libre</strong>. Es la opción que permite insertar el contenido HTML de la pieza.</p>'+
'<figure class="tutorial-shot"><a href="images/xalok-02-libre.jpeg" target="_blank" rel="noopener" aria-label="Ampliar captura: plantilla Libre"><img src="images/xalok-02-libre.jpeg" width="1600" height="739" alt="Selector de plantillas de Xalok con las opciones Icono, Cuadrada, Panorámica y Libre" loading="lazy"></a><figcaption>Selector de plantilla · Elegir Libre <span>Haz clic en la captura para ampliarla</span></figcaption></figure>'+
'<h2>4. Pegar el código</h2><p>Abre la edición del bloque HTML mediante el icono de edición situado en la parte superior derecha del bloque. En el panel, localiza <strong>«Coloca aquí el código embed»</strong>, sustituye el texto de ejemplo por todo el código del archivo preparado por el proveedor y guarda el cambio.</p>'+
'<figure class="tutorial-shot"><a href="images/xalok-03-codigo.jpeg" target="_blank" rel="noopener" aria-label="Ampliar captura: campo del código HTML"><img src="images/xalok-03-codigo.jpeg" width="1600" height="757" alt="Panel de edición del bloque Libre, con el área Coloca aquí el código embed para pegar el HTML" loading="lazy"></a><figcaption>Bloque Libre · Pegar el código en el área de texto <span>Haz clic en la captura para ampliarla</span></figcaption></figure>'+
'<p>El campo <code>free_html_height</code> no es el área para pegar el código. Si la entrega requiere un ajuste de altura, el proveedor debe indicarlo expresamente.</p>'+
'<h2>5. Completar sección, metas, palabras clave y streaming</h2><p>Rellena los datos editoriales y la configuración de la noticia. Las pestañas superiores incluyen Datos básicos, Metadata, SEO y Otras opciones; comprueba que la información queda guardada en los campos correspondientes.</p>'+
table(['Dato','Qué debe indicar el PM'],[['Medio de publicación','La Vanguardia (LV), Mundo Deportivo (MD) o ambos. Este tutorial muestra la integración en LV.'],['Sección','La sección asignada a la noticia.'],['Titular y descripción SEO','Los textos definitivos para configurar las metas de la noticia.'],['Palabras clave','Las palabras acordadas, incluyendo siempre brl al final.'],['Streaming','Indicar si el contenido incluye un vídeo largo. En ese caso, añadir la palabra streaming o seleccionar la opción correspondiente en Xalok para evitar que la página se recargue automáticamente. Mantener siempre brl al final de las palabras clave.'],['Fecha de publicación','El día acordado. Hora habitual: aproximadamente las 05:50.']])+
'<p>Guarda la noticia y comprueba la URL final generada una vez completados estos datos. Confirma la cabecera, la sección y la terminación esperada con <code>brl</code>. Comunica la URL al PM y actualiza cualquier enlace del proyecto que deba apuntar a ella. Tener una URL generada no significa que la noticia ya esté publicada.</p>'+
'<h2>6. Revisar la integración dentro de Xalok</h2><p>Abre la previsualización interna y recorre toda la pieza. Comprueba anchura, márgenes, tipografías, imágenes, vídeos, enlaces y comportamiento al hacer scroll, en móvil y escritorio. No envíes este enlace al cliente: no tiene acceso.</p><p>Si algo difiere del diseño aprobado o de la URL de prueba, envía la incidencia al proveedor. El PM no tiene que reparar el código. Después de cualquier corrección, sustituye el fragmento completo si el proveedor lo indica y vuelve a revisar.</p>'+
'<h2>7. Programar y comprobar la publicación</h2><p>Con la aprobación final y los datos completos, programa el día acordado a las <strong>05:50 aproximadamente</strong> y confirma la programación al PM. Tras la salida, revisa la URL publicada: contenido, enlaces, recursos y funcionamiento.</p>'+
'<details class="technical"><summary>Referencia técnica para proveedores: fragmento y ajustes de LV</summary><h3>Qué contiene el fragmento</h3><p>El patrón de integración incluye los recursos de estilos, el contenedor del contenido y el comportamiento de la pieza. Los ajustes del CMS se añaden solo si son necesarios. No se pega un documento completo con html, head y body dentro de otro documento.</p>'+code("""<!-- Esquema orientativo: sustituir las URLs de ejemplo. -->
<link rel="stylesheet" href="https://example.com/proyecto/main.css">
<div class="bc-proyecto" data-bc-project="proyecto">
  <!-- HTML aprobado -->
</div>
<script src="https://example.com/proyecto/scripts.js"></script>""")+
'<h3>Identificar el artículo que contiene la pieza</h3><p>En integraciones anteriores se comprobó que un identificador presente en la preview no existía en la página publicada. El patrón <code>article.visual__story--free:has(.bc-proyecto)</code> identifica el artículo por la raíz del contenido. Verifica siempre que coincida con el DOM real.</p>'+code(fix)+
note('No es un reset obligatorio','Sustituye .bc-proyecto por la raíz real y revisa qué elementos coinciden. Las reglas sobre .row o .container-fluid también pueden alcanzar clases internas de la pieza. Ajusta solo los wrappers necesarios. El overflow visible se utilizó para resolver sticky; no lo apliques por rutina ni traslades estos selectores a MD sin comprobar su plantilla.')+'</details>')
section('revision','Control de calidad / Antes y después','Qué comprobar para cerrar la entrega.','Una revisión visual del PM y una comprobación técnica del proveedor se complementan. Marca cada punto como correcto, pendiente o no aplicable en el informe de entrega.',
'<h2>Revisión de contenido · PM</h2><p>Confirmar el OK del diseño, la revisión de la URL externa y la aprobación final del cliente antes de programar.</p><ul class="checklist"><li>Última versión aprobada de textos, imágenes, marca y créditos.</li><li>Medio de publicación (LV, MD o ambos), sección, titular y descripción SEO y palabras clave terminadas en brl confirmados. Si hay un vídeo largo, streaming configurado para evitar la recarga automática.</li><li>Fecha de salida acordada y programación habitual a las 05:50 aproximadamente.</li><li>Todos los botones y enlaces comprobados; sin destinos provisionales activos.</li><li>Contenido legible en móvil y escritorio, sin textos cortados.</li><li>Vídeos e interacciones responden como espera el lector.</li><li>Estado de capítulos publicados y próximos coherente.</li></ul>'+
'<h2>Revisión técnica · Proveedor / integración</h2><ul class="checklist"><li>CSS y JavaScript aislados; no alteran elementos del medio.</li><li>Recursos cargan desde las URLs definitivas, sin 404 ni errores propios bloqueantes.</li><li>Comprobado en anchuras de 375, 768, 1024 y 1440 píxeles.</li><li>Sin desbordamiento horizontal accidental, solapamientos o imágenes deformadas.</li><li>Scroll normal, scroll rápido, anclas y elementos sticky comprobados dentro de Xalok.</li><li>Contenido esencial visible si falla JavaScript o una animación.</li><li>Teclado, foco visible y movimiento reducido revisados.</li><li>IDs, encabezados, textos alternativos y controles revisados.</li><li>Revisión repetida en la URL publicada.</li></ul>'+
'<h2>Cómo comunicar el resultado</h2>'+table(['Estado','Qué significa','Acción'],[['<span class="badge error">Error</span>','Rompe el contenido, impide una acción esencial o afecta al medio.','Corregir antes de dar la pieza por lista.'],['<span class="badge pending">Advertencia</span>','Riesgo o pendiente que necesita una decisión.','Identificar impacto, responsable y resolución acordada.'],['<span class="badge ok">Correcto</span>','Comprobación realizada y superada.','Indicar entorno y versión revisados.'],['No comprobado','No se tuvo acceso o faltaban recursos para probarlo.','No presentarlo como correcto; asignar la revisión.']])+
'<p>Si una auditoría solo lee archivos, debe decirlo. No puede certificar responsive, consola, carga real o interacciones sin observarlos en ejecución.</p><p><a class="text-link" href="#incidencias">Consultar qué actualizar en cada tipo de cambio</a></p>')
section('incidencias','Mantenimiento / Diagnóstico','Actualizar sin perder la versión aprobada.','Primero identifica si el cambio está en el HTML de Xalok, en un recurso externo o en ambos.',
table(['Cambio','Acción habitual','Qué verificar'],[['Texto o enlace en el HTML integrado','Actualizar la fuente y el fragmento guardado en Xalok.','Que ambas versiones coincidan y el enlace final funcione.'],['CSS, JS, imagen o vídeo externo','Publicar la actualización en el alojamiento de recursos.','Que se sirva la nueva versión; revisar caché y páginas que comparten el archivo.'],['URL o nombre de un recurso','Actualizar la referencia donde se utiliza.','Puede requerir nuevo pegado de HTML, actualización de CSS o de JS.'],['Solo ajuste inline en Xalok','Actualizar el fragmento y conservar la versión final de entrega.','Que la próxima entrega no sobrescriba el arreglo.'],['Nueva funcionalidad o cambio de diseño','Actualizar los archivos afectados y repetir las pruebas pertinentes.','Integración real en Xalok y nueva revisión del resultado.']])+
note('Subir archivos puede cambiar una noticia ya publicada','Si la noticia apunta a esos mismos recursos, una actualización puede reflejarse sin volver a publicar el HTML. Acordad el momento del cambio y conservad una versión recuperable. No sobrescribáis archivos compartidos sin comprobar dónde se usan.')+
'<h2>Problemas habituales</h2><details open><summary>En el servidor se ve bien, pero en LV faltan estilos o imágenes</summary><p>Comprobar las URLs desde la página del medio, la publicación de recursos y las peticiones fallidas. Revisar rutas relativas del HTML y URLs construidas por JavaScript. Tener el archivo en GitHub no garantiza que su URL pública esté sirviéndose.</p></details><details><summary>Aparecen márgenes o el sticky deja de funcionar</summary><p>Inspeccionar los contenedores externos, sus paddings, márgenes y overflow. Aplicar solo el ajuste acotado que resuelva el problema. Verificar después que no se altera otro módulo. Consultar el patrón de referencia de LV.</p></details><details><summary>Parte del contenido desaparece al hacer scroll</summary><p>Revisar estados ocultos de animación, errores JavaScript y cálculos de posición. Probar scroll rápido y enlaces a secciones. El texto debe permanecer accesible aunque falle el efecto.</p></details><details><summary>El cambio está subido, pero se sigue viendo la versión anterior</summary><p>Verificar la URL exacta que utiliza la noticia y que la publicación de recursos haya terminado. Comprobar caché antes de volver a cambiar código. Si se versiona una URL, actualizar también su referencia.</p></details><details><summary>Se duplican titulares o elementos del medio</summary><p>Comprobar qué procede del HTML y qué añade la plantilla editorial. Coordinar la configuración correcta con quien gestiona Xalok. No ocultar elementos globales del medio con un selector genérico.</p></details>'+
'<h2>Una incidencia útil incluye</h2><p>URL y versión, sección afectada, qué sucede, qué debería suceder, pasos para reproducirlo, dispositivo y navegador, y una captura o vídeo cuando ayude. En incidencias técnicas, añadir el error o recurso afectado.</p>')
section('md','Mundo Deportivo / Próxima ampliación','La misma base. Su propia integración.','El proceso editorial y las entregas pueden reutilizarse. Los detalles de la plantilla de Mundo Deportivo necesitan una comprobación independiente.',
note('Integración MD pendiente de validar','Todavía no hay un ejemplo ni capturas de MD en la documentación aportada. Esta sección no autoriza a reutilizar los selectores de LV en Mundo Deportivo.')+
'<div class="split"><div><h2>Ya se puede aplicar</h2><ul><li>Los dos circuitos de entrega.</li><li>Enlace de revisión y versión identificada.</li><li>Recursos públicos y aislamiento del contenido.</li><li>Coordinación y checklist de PM.</li><li>Pruebas móviles, de enlaces y de accesibilidad.</li></ul></div><div><h2>Falta documentar</h2><ul><li>Tipo de noticia y configuración de BC.</li><li>Campo o bloque HTML y recorrido de inserción.</li><li>Contenedores y estilos de la plantilla.</li><li>Identificación comercial, cabecera y créditos.</li><li>Previsualización, programación y prueba publicada.</li></ul></div></div><h2>Con qué completaremos esta sección</h2><p>Un HTML de ejemplo, una URL de MD y las capturas del flujo real permitirán adaptar el tutorial. Cada ajuste se documentará con su motivo y una prueba en la página publicada.</p>')
section('recursos','Recursos / Buenas prácticas','Herramientas y prácticas útiles','Apoyos para diseñar, revisar y entregar contenidos que funcionen dentro del medio.',
'<p><a class="text-link" href="#descargas">Descargar la plantilla y los archivos de ayuda</a></p><h2>Diseño y feedback con Figma</h2><p>Se recomienda <a href="https://www.figma.com/design/" target="_blank" rel="noopener">Figma Design</a> para preparar las versiones de escritorio y móvil y compartir el mockup con el cliente a través del PM. Mantén una referencia clara del diseño aprobado y comprueba los permisos del enlace antes de enviarlo.</p><p>Deja los comentarios vinculados a la sección correspondiente, intenta agruparlos cuando el tiempo de ejecución lo permita y explica las interacciones previstas. El prototipo ayuda a mostrar el recorrido, pero la web desarrollada se revisa después en su URL externa.</p>'+
'<h2>Prácticas que facilitan la entrega</h2>'+table(['Práctica','Cómo aplicarla'],[['Una versión de referencia','Identificar qué diseño está aprobado, qué URL muestra la última maqueta y qué HTML corresponde a la entrega. Evitar archivos finales con nombres ambiguos.'],['Preparar escritorio y móvil desde el diseño','Acordar el orden de lectura y la adaptación de módulos antes de maquetar. No reducir sin más la composición de escritorio.'],['Compartir assets listos para web','Entregar imágenes con el encuadre y calidad necesarios, dimensiones coherentes y nombres reconocibles. Mantener originales y exportaciones diferenciados.'],['Aislar cada proyecto','Usar un contenedor propio, CSS acotado y JavaScript que actúe solo dentro de la pieza.'],['Publicar recursos antes de integrar','Comprobar que las URLs definitivas de CSS, JS, imágenes y vídeos responden antes de pegar el HTML en Xalok.'],['Animar como mejora','El contenido debe poder leerse si falla el efecto. Revisar scroll rápido, anclas y movimiento reducido.'],['Revisar en el contexto real','Comparar la maqueta externa, la preview interna y la página publicada. Cada una puede tener un contexto distinto.'],['Conservar una versión recuperable','Antes de modificar recursos utilizados por una noticia publicada, guardar la versión anterior e identificar las páginas afectadas.'],['Documentar lo que importa','Anotar recursos, dependencias, versión, enlaces y cambios de mantenimiento. Un README breve puede evitar dudas al actualizar meses después.']])+
'<h2>Cómo dar feedback útil</h2><p>Indica sección, dispositivo, problema y resultado esperado. Por ejemplo: «En móvil, en la tarjeta del capítulo 2, el titular queda cortado; debe poder leerse completo». Añade captura y URL. Para cambios de contenido, entrega el texto nuevo completo y aprobado.</p><p>El PM prioriza las observaciones e intenta agruparlas cuando el tiempo de ejecución lo permite; el proveedor indica qué ha corregido y dónde revisar la nueva versión. Cerrar una ronda significa resolver sus puntos o dejar una decisión explícita sobre los restantes.</p>'+
'<h2>Editores de código</h2><p>Opciones para abrir, revisar y desarrollar los archivos. La elección depende del equipo.</p>'+table(['Opción','Uso habitual','Web oficial'],[['Visual Studio Code','Edición de HTML, CSS y JavaScript con extensiones.','<a href="https://code.visualstudio.com/" target="_blank" rel="noopener">Visual Studio Code</a>'],['Sublime Text','Edición directa de archivos de texto y código.','<a href="https://www.sublimetext.com/" target="_blank" rel="noopener">Sublime Text</a>'],['WebStorm','Entorno de desarrollo orientado a JavaScript y TypeScript.','<a href="https://www.jetbrains.com/webstorm/" target="_blank" rel="noopener">WebStorm</a>'],['Cursor','Edición de código con asistencia de IA.','<a href="https://cursor.com/" target="_blank" rel="noopener">Cursor</a>']])+
'<p class="small">Consulta las condiciones actuales en las webs oficiales. La asistencia de IA no sustituye la comprobación del código ni la prueba dentro del medio.</p>')
section('descargas','Proveedores / Kit de referencia','Plantilla y archivos de ayuda','Un ejemplo completo para preparar el fragmento HTML que se pega en Xalok, con documentación y comprobaciones reutilizables.',
note('Una entrega completa de demostración','El archivo contiene una pieza terminada con contenido neutro, estilos e interacción reales. Empieza con el ajuste de Xalok y se puede copiar completo al bloque HTML para una prueba. No tiene textos por rellenar ni URLs ficticias. La vista previa muestra la pieza fuera del CMS; su integración debe comprobarse dentro de LV.')+
'<div class="download-hero"><div><span class="kicker">Kit para proveedores</span><h2>Todo lo necesario en un ZIP</h2><p>HTML completo, imagen de ejemplo con URL absoluta, vista previa, estilos, script, guía de integración, checklist y reglas para asistentes.</p></div><a class="download-button" href="downloads/kit-xalok.zip" download="kit-xalok.zip">Descargar kit completo</a></div>'+
'<p><a class="text-link" href="downloads/kit-xalok/vista-previa.html" target="_blank" rel="noopener">Abrir la vista previa de la entrega</a></p><h2>Descargas individuales</h2>'+table(['Archivo','Para qué sirve','Descarga'],[
['ejemplo-xalok.html','Entrega completa: ajuste de LV, CSS, fuente pública, contenido y JS. Copiar todo el archivo al campo HTML de Xalok; sin html, head o body.','<a href="downloads/kit-xalok/ejemplo-xalok.html" download="ejemplo-xalok.html">Descargar HTML</a>'],
['guia-integracion.md','Cómo leer y probar la entrega, qué copiar a Xalok y cómo separar los recursos en una entrega con alojamiento propio.','<a href="downloads/kit-xalok/guia-integracion.md" download="guia-integracion.md">Descargar guía</a>'],
['checklist-xalok.md','Comprobaciones de entrega, aislamiento, recursos, responsive, accesibilidad y publicación.','<a href="downloads/kit-xalok/checklist-xalok.md" download="checklist-xalok.md">Descargar checklist</a>'],
['reglas-para-asistentes.md','Instrucciones opcionales para adjuntar como contexto a un asistente de desarrollo, independientemente del editor.','<a href="downloads/kit-xalok/reglas-para-asistentes.md" download="reglas-para-asistentes.md">Descargar reglas</a>'],
['ajustes-lv-opcionales.css','Reglas de referencia para wrappers de LV, comentadas. Activar solo lo necesario tras comprobar el DOM.','<a href="downloads/kit-xalok/ajustes-lv-opcionales.css" download="ajustes-lv-opcionales.css">Descargar ajustes LV</a>'],
['assets/css/main.css','Copia de los estilos ya incluidos en el HTML. Útil para estudiar o externalizar el CSS sin duplicarlo.','<a href="downloads/kit-xalok/assets/css/main.css" download="main.css">Descargar CSS</a>'],
['assets/js/scripts.js','Script real del botón Abrir/cerrar todas las claves. Ya está incluido al final del HTML.','<a href="downloads/kit-xalok/assets/js/scripts.js" download="scripts.js">Descargar JS</a>']])+
'<h2>Una imagen con URL absoluta</h2><p>La ilustración de la demo se carga desde GitHub Pages con una URL HTTPS completa en <code>src</code>. Busca <code>composicion-editorial.svg</code> en el HTML: incluye <code>alt</code>, <code>width</code>, <code>height</code> y carga diferida. El ZIP contiene también el archivo original. Para una pieza real, publica la imagen en el alojamiento del proyecto y cambia la URL por la suya.</p><h2>Cómo usar el kit</h2>'+steps([
('Ver el resultado y abrir el código','Abre la vista previa y prueba los capítulos, los desplegables y el botón que abre todas las claves. Descarga ejemplo-xalok.html y ábrelo en un editor para ver el archivo que se entrega.'),
('Reconocer las partes de la entrega','El orden es: style con ajuste de LV y estilos de la pieza, link a la fuente pública, div raíz con todo el contenido y script final. El CSS y el JS están incluidos para que la demo funcione sin alojar recursos por separado.'),
('Copiar el archivo completo en una prueba de Xalok','Copia todo el código de ejemplo-xalok.html, desde style hasta el cierre del script. Pégalo en una Visual story con plantilla Libre y revisa el resultado. vista-previa.html es una página completa para navegador y no se pega en el CMS.'),
('Preparar una pieza real siguiendo la misma estructura','Usa el diseño y los contenidos aprobados y una raíz exclusiva. Si separas CSS y JS, publícalos en tu alojamiento público y sustituye solo sus bloques por referencias absolutas. Comprueba los ajustes de wrappers en el CMS; usa los recursos publicados en el repositorio de cada proyecto.')])+
'<details><summary>Ver el código completo del ejemplo</summary>'+code((p/'downloads/kit-xalok/ejemplo-xalok.html').read_text())+'</details>'+
note('Para el PM','Recibe del proveedor el HTML final preparado para Xalok; no necesitas adaptar esta plantilla. El ejemplo es una entrega de demostración, no una noticia de cliente. Los archivos .md son documentos de texto que se abren en un editor. Las reglas para asistentes son una ayuda opcional, no un requisito de entrega.')+
'<p><a class="text-link" href="#xalok">Consultar el tutorial de integración en LV</a></p>')
sections = [(i, t.rstrip('.'), re.sub(r'\.(</h[1-6]>)', r'\1', h)) for i,t,h in sections]
nav=[('inicio','Empezar aquí'),('pms','Guía para PMs'),('diseno','Diseño y aprobación'),('entregas','Entregas y responsables'),('requisitos','Requisitos técnicos'),('xalok','Integración en LV'),('revision','Checklist de revisión'),('incidencias','Cambios e incidencias'),('md','Mundo Deportivo'),('recursos','Recursos'),('descargas','Plantilla y archivos')]
html='''<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>BC · Guía de contenidos HTML</title><meta name="description" content="Guía para PMs y proveedores de Branded Content: entregas, integración HTML en Xalok y revisión en La Vanguardia y Mundo Deportivo."><meta name="robots" content="noindex,nofollow"><link rel="icon" type="image/svg+xml" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 40 40'%3E%3Crect width='40' height='40' rx='8' fill='%23ff0000'/%3E%3Cpath d='M10 10v20h9a6 6 0 0 0 0-12h-9m0 0h8a4 4 0 0 0 0-8z' fill='none' stroke='white' stroke-width='3'/%3E%3C/svg%3E"><link rel="stylesheet" href="styles.css?v=20261002-1"><script src="app.js" defer></script></head><body><a class="skip" href="#contenido">Saltar al contenido</a><header class="topbar"><a class="brand" href="#inicio" aria-label="Branded Content, inicio"><span class="logo">Branded Content</span><span class="brand-description">Guía de contenidos HTML</span></a><span class="top-meta">BRANDSLAB <span>/</span> GODÓ NEXUS</span></header><div class="layout"><aside class="sidebar"><div class="side-label">GUÍA DE TRABAJO</div><nav aria-label="Secciones de la guía">'''+''.join((f'<span class="nav-disabled" aria-disabled="true"><span class="nav-index">{i+1:02}</span><span>{label}<small>Próximamente</small></span></span>' if id == "md" else f'<a href="#{id}"><span class="nav-index">{i+1:02}</span>{label}</a>') for i,(id,label) in enumerate(nav))+'''</nav><div class="side-bottom"><span class="badge">Guía de trabajo</span><p>La Vanguardia<br>Mundo Deportivo · Próximamente</p></div></aside><main id="contenido"><div class="page-top"><span class="breadcrumb">BC / Manual de producción</span><button class="print" type="button">Imprimir sección</button></div>'''+''.join(s[2] for s in sections if s[0] != 'md')+'''<footer><span>Brandslab · Guía de contenidos HTML</span><a href="#inicio">Inicio de la guía</a></footer></main></div></body></html>'''
(p/'index.html').write_text(html)

# Rebuild the downloadable archive from the tracked source files.
from zipfile import ZipFile, ZIP_DEFLATED
kit = p / 'downloads/kit-xalok'
with ZipFile(p / 'downloads/kit-xalok.zip', 'w', ZIP_DEFLATED) as archive:
    for file in sorted(kit.rglob('*')):
        if file.is_file():
            archive.write(file, file.relative_to(p / 'downloads'))
